"""PlatformIO pre-build script: gzip web/index.html into a PROGMEM header.

Generates include/dashboard_html_gz.h with:
    const uint8_t DASHBOARD_HTML_GZ[] PROGMEM = {...};
    const size_t  DASHBOARD_HTML_GZ_LEN = ...;

The header is regenerated only when web/index.html is newer than it.
Can also be run standalone: python tools/build_web.py
"""
import gzip
import os

try:
    Import("env")  # noqa: F821  (provided by PlatformIO/SCons)
    PROJECT_DIR = env["PROJECT_DIR"]  # noqa: F821
except NameError:
    PROJECT_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SRC = os.path.join(PROJECT_DIR, "web", "index.html")
DST = os.path.join(PROJECT_DIR, "include", "dashboard_html_gz.h")


def build():
    if os.path.exists(DST) and os.path.getmtime(DST) >= os.path.getmtime(SRC):
        return
    with open(SRC, "rb") as f:
        raw = f.read()
    # mtime=0 keeps the output deterministic between builds
    data = gzip.compress(raw, compresslevel=9, mtime=0)

    lines = []
    for i in range(0, len(data), 20):
        lines.append("    " + ", ".join("0x%02x" % b for b in data[i:i + 20]) + ",")

    with open(DST, "w", encoding="utf-8", newline="\n") as f:
        f.write("// AUTO-GENERATED by tools/build_web.py from web/index.html - DO NOT EDIT\n")
        f.write("#pragma once\n#include <Arduino.h>\n\n")
        f.write("// Uncompressed: %d bytes, gzip: %d bytes\n" % (len(raw), len(data)))
        f.write("const uint8_t DASHBOARD_HTML_GZ[] PROGMEM = {\n")
        f.write("\n".join(lines))
        f.write("\n};\nconst size_t DASHBOARD_HTML_GZ_LEN = %d;\n" % len(data))
    print("[build_web] %s: %d -> %d bytes (gzip)" % (os.path.relpath(DST, PROJECT_DIR), len(raw), len(data)))


build()
